### PR TITLE
Development

### PR DESCRIPTION
**Pull request by pxseu**

### CODE REVIEW

**Comment by pxseu** [comment]
po chuj sie pierdole z tym

**Comment by rxri** [comment]
No one knows.

**Comment by pxseu** [comment]
co ty tu robisz

**Comment by pxseu** [comment]
moje repo

**Comment by rxri** [comment]
I'm sitting on chair, wbu

**Comment by pxseu** [comment]
in a chair, and same.

**Comment by rxri** [comment]
In a chair? Wtf man.

**Comment by pxseu** [comment]
You can sit in an arm chair for example.
Or on a chair.
but I dont think at is corrext

**Comment by rxri** [comment]
So it should be ``on a chair`` I fixed my comment too because I said ``at`` instead of ``on``. So don't freaking say that you are sitting in a chair lol

**Comment by pxseu** [comment]
If it's a flat chair you sit on it. If it's something that covers you from almost three sides you sit in it.

**Comment by rxri** [comment]
Wtf

**Comment by jelni** [comment]
Pull request successfully merged and closed
You’re all set—the development branch can be safely deleted.

**Comment by jelni** [comment]
wait what

**Comment by pxseu** [comment]
DEBILU

**Comment by indexerrowaty** [comment]
Idk what to say so I'm just going to send a beautiful Eric Siu pic.

9F3D4B5C-7E44-41A5-8DF0-021A1E2D3538

**Comment by pxseu** [comment]
Dziękuję

**Pull request merged**
