### PR TITLE
spooky mode!

### PR DESCRIPTION
**Pull request by hexiro**
puts the "HELL-YEAH-BABY-CSS" class to some good use by giving it the following css:

```css
.HELL-YEAH-BABY-CSS {
	filter: brightness(0.8) grayscale(0.8) blur(1px);
}
```

### CODE REVIEW

**Comment by hexiro** [comment]
omg @Hexiro thank you for this pull request! this is what i've been looking for! lgtm!

**Comment by pxseu** [comment]
omg @Hexiro thank you for this pull request! this is what i've been looking for! lgtm!

**Review by pxseu — APPROVED** [review]
even though this won't change anything will be left as a legacy feature

**Comment by pxseu** [comment]
@JelNiSlaw approve and squash k thx bye <3333333

**Comment by hexiro** [comment]
yes yes yes

**Comment by hexiro** [comment]
thank you guys ❤️ 😅

**Review by looskie — COMMENTED** [review]
LBTM

**Comment by pxseu** [comment]
> LBTM

bro

**Review by jelni — COMMENTED** [review]
Thank you for your contribution. Unfortunately this bad @pxseu guy merged this for me!

**Review by hexiro — COMMENTED** [review]
LGTM!

**Pull request merged**
